# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a0a646c9e34c00ef19ad37b2fbe1b2f0816d9ae7836da6ca49b02a1b93f750dbe4ee6a3f712c278dc435201c9071d1b1f35837b131f908b87a184f2440cd86f

test:
  secret_key_base: eb0caf21b36ebe228a70d69d756b5178c3839f026bc405fb63be24be5c35280cf71003d0dca61e835bc376c318a525b07d71c75f357382e242853ab0275b466b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
